apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector: 
    app: jenkins-server
  type: NodePort  
  ports:
    - name: "https"
      port: 443
      targetPort: 443
      nodePort: 32000
    - name: "tcpraw"
      port: 31485
      targetPort: 31485
      nodePort: 31485

