apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted-flask
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: noted-flask
  template:
    metadata:
      labels:
        app: noted-flask
    spec:
      containers:
      - image: docker.io/debuglachy/noted-flask-app:7e17dc8713cda8def57896b458059410176a70ba
        name: noted-flask
        ports:
        - containerPort: 8080
