apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted-flask
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: noted-flask
  template:
    metadata:
      labels:
        app: noted-flask
    spec:
      containers:
      - image: docker.io/debuglachy/noted-flask-app:097cc7ac543a02a1133211e4ef2ddc36f32fb9d8
        name: noted-flask
        ports:
        - containerPort: 8080
