apiVersion: apps/v1
kind: Deployment
metadata:
  name: noted-flask
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: noted-flask
  template:
    metadata:
      labels:
        app: noted-flask
    spec:
      containers:
      - image: docker.io/debuglachy/noted-flask-app:8a9b0404a321b9afe39656059e67354361947dfe
        name: noted-flask
        ports:
        - containerPort: 8080
