name: Reusable Docker Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      run_token:
        required: true

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: x-access-token
          password: ${{ inputs.run_token }}
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:main
          docker push ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:main
