name: Reusable Docker Publish

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
    secrets:
      APP_ID:
        required: true
      APP_PRIVATE_KEY:
        required: true

permissions:
  contents: write
  packages: write
  attestations: write

jobs:
  get-token-and-build-image:
    runs-on: ubuntu-latest
    steps:
      - id: get-token
        name: get-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: x-access-token
          password: ${{ steps.get-token.outputs.token }}
      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:main
          docker push ghcr.io/${{ github.actor }}/${{ inputs.image_name }}:main
