name: Reusable Python Package

on:
  workflow_call:
    inputs:
      python_version:
        required: true
        type: string
      src_folder:
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

jobs:
  package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Get code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python_version }}
    - name: Get lint dependency
      run: python -m pip install pre-commit
    - name: Lint conventional commit syntax
      run: |
        (git rev-parse --verify -q HEAD^2{commit} \
        && git log -1 --pretty=%B HEAD^2 > /tmp/COMMIT_MSG \
        && pre-commit run --hook-stage commit-msg --commit-msg-filename /tmp/COMMIT_MSG) \
        || echo
    - name: Get app dep
      run: |
        python -m pip install -r requirements.txt
        python -m pip install pytest==8.4.1
        python -m pip install coverage==7.9
        python -m pip install pytest-cov==6.2.1
    - name: Check coverage
      run: python -m pytest -v --cov=${{ inputs.src_folder }}
    - name: Comment coverage
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ github.token }}
        MINIMUM_GREEN: 90
        MINIMUM_ORANGE: 70
        VERBOSE: true
    - name: Fail low coverage
      run: coverage report --fail-under=90
